- name: Listen for newly added ConfigMap resources
  hosts: all
  sources:
    - junipernetworks.eda.k8s:
        api_version: v1
        kind: ConfigMap
  rules:
    - name: Notify
      condition: event.type == "ADDED"
      action:
        debug: 
