---
- name: Listen for PoD events
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Pod
        label_selectors:
          - type=eda
  rules:
    - name: Trigger action on PoD Deletion 
      condition: event.type == "DELETED"
      action:
        run_job_template:
          name: delete-pod.yml
          organization: Default
          job_args:
            extra_vars: 
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
