---
- name: Listen for Namespace events
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Namespace
  rules:
    - name: Trigger action on Namespace creation or update with specific annotation
      condition: 
        all:
          - event.type == "ADDED" or event.type == "MODIFIED"
      action:
        run_job_template:
          name: apstra-bp.yml
          organization: Default
          job_args:
            extra_vars: 
              ns: "{{ event.resource.metadata.name }}"
