---
- name: Listen for Namespace events
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Namespace
  rules:
    - name: Trigger action on Namespace creation or update with specific annotation
      condition: event.type == "ADDED" and event.resource.metadata.labels.type == eda
      action:
        run_job_template:
          name: apstra-bp.yml
          organization: Default
          job_args:
            extra_vars: 
              ns: "{{ event.resource.metadata.name }}"
              annotations: "{{ event.resource.metadata.annotations }}"
