---
- name: Listen for newly created Namespace
  hosts: all
  sources:
    - junipernetworks.eda.k8s:
        api_version: v1
        kind: Namespace
  rules:
    - name: Notify
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: test.yml
          organization: Default
          job_args:
            extra_vars: 
              ns: "{{ event.resource.metadata.name }}"
