- name: Listen for newly created Namespace
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Namespace
  rules:
    - name: Notify
      condition: event.type == "ADDED"
      action:
        debug:
