---
- name: Listen for newly created Namespace
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Namespace
  rules:
    - name: Notify
      condition: event.type == "ADDED"
      action:
        debug:
    - name: Set Resource Quotas to a Namespace
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: ns-quota.yml
          organization: Default
          job_args:
            extra_vars: 
              ns: "{{ event.resource.metadata.name }}"
