---
- name: Listen for PoD events
  hosts: all
  sources:
    - junipernetworks.eda.k8s:
        api_version: v1
        kind: Pod
        log_level: DEBUG
        label_selectors:
          - type=eda
  rules:
    - name: Trigger action on PoD creation 
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: pod-create.yml
          organization: Default
          job_args:
            extra_vars: 
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
