---
- name: Listen for SriovNetwork events
  hosts: all
  sources:
    - junipernetworks.eda.k8s:
        api_version: sriovnetwork.openshift.io/v1
        kind: SriovNetwork
        label_selectors:
          - type=eda
  rules:
    - name: Trigger action on  SriovNetwork creation or update with specific annotation
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: create-vnet.yml
          organization: Default
          job_args:
            extra_vars: 
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
