---
- name: Listen for Namespace events
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: k8s.cni.cncf.io/v1
        kind: NetworkAttachmentDefinition
  rules:
    - name: Trigger action on  SriovNetwork creation or update with specific annotation
      condition: event.type == "ADDED" and event.resource.metadata.labels.type == eda
      action:
        run_job_template:
          name: create-vnet.yml
          organization: Default
          job_args:
            extra_vars: 
              ns: "{{ event.resource.metadata.name }}"
              annotate: "{{ event.resource.metadata.annotations }}"
              ev: "{{ event }}"
