---
- name: publish updated policy
  hosts: localhost
  connection: httpapi
  gather_facts: no
  vars:
    namespace: "{{ ns }}"

  tasks:
    - name: get list of blueprint
      uri:
        url: "https://10.88.140.218/api/blueprints"
        method: GET
        follow_redirects: all
        return_content: yes
        status_code: 200
        headers:
          Content-Type: application/json
          AUTHTOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidXNlcl9zZXNzaW9uIjoiOTgyYjU3MjgtNzE0Yy00NmY5LWE5NjEtZDM2NjBiNDMxYmQ2IiwiY3JlYXRlZF9hdCI6IjIwMjQtMDgtMTNUMDg6NDM6NTkuNTkwNTg5IiwiZXhwIjoxNzIzNjI1MDM5fQ.C-4eetor_5RVCbgwjKVZ46vKNeMyiC6JJuz8iEO598iVRv0g647TgZOBFKjF7FXJxstVxkdjUH-BD6Dbsqi8MA
        validate_certs:  false
      register: blueprint
      
    - name: display list of blueprint0
      debug:
        msg: "{{ blueprint.json['items'][0].label }}"

    - name: display list of blueprint1
      debug:
        msg: "{{ blueprint.json['items'][1].label }}"

    - name: create blueprint
      uri:
        url: "https://10.88.140.218/api/blueprints"
        method: POST
        follow_redirects: all
        return_content: yes
        status_code: 201
        body_format: json
        body: "{\"id\": \"{{ namespace }}\", \"label\": \"{{ namespace }}\", \"design\": \"freeform\", \"init_type\": \"default\"}"
        headers:
          Content-Type: application/json
          AUTHTOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidXNlcl9zZXNzaW9uIjoiOTgyYjU3MjgtNzE0Yy00NmY5LWE5NjEtZDM2NjBiNDMxYmQ2IiwiY3JlYXRlZF9hdCI6IjIwMjQtMDgtMTNUMDg6NDM6NTkuNTkwNTg5IiwiZXhwIjoxNzIzNjI1MDM5fQ.C-4eetor_5RVCbgwjKVZ46vKNeMyiC6JJuz8iEO598iVRv0g647TgZOBFKjF7FXJxstVxkdjUH-BD6Dbsqi8MA
        validate_certs:  false
    
