---
- name: publish updated policy
  hosts: localhost
  gather_facts: no

  tasks:
    - name : login
      uri:
        url: "https://{{ 10.88.140.218 }}/user/login"
        method: POST
        follow_redirects: all
        return_content: yes
        status_code: 201
        force_basic_auth: yes
        validate_certs: false
        headers:
          Content-Type: application/json
        body_format: json
        body: { "username": "{{ admin }}", "password": "{{ Embe1mpls@apstra }}" }
      register: login


    - name: get list of blueprint
      uri:
        url: "https://{{ 10.88.140.218 }}/blueprints"
        method: GET
        follow_redirects: all
        return_content: yes
        status_code: 200
        headers:
          Content-Type: application/json
          AUTHTOKEN: "{{ login.json.token }}"
        validate_certs:  false
      register: blueprint
