---
- name: Gather Apstra facts
  hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - junipernetworks.apstra
    - ansible.eda
    - dynatrace.event_driven_ansible
    - kubealex.eda
    - kubealex.general
    - redhatinsights.eda
    - sabre1041.eda
    - community.general
  environment:
    APSTRA_API_URL: "https://10.87.2.40/api"
    APSTRA_USERNAME: "admin"
    APSTRA_PASSWORD: "Apstramarvis@123"
    APSTRA_VERIFY_CERTIFICATES: 0
  vars:
    namespace: "{{ ns }}"
    annotations: "{{ annotate }}"
  tasks:
    - name: Print vrf specific to the namespace
      debug:
        msg: "{{ annotations['k8s.v1.cni.cncf.io/vrf']}}"

    - name: Print vrf specifics to the namespace
      debug:
        msg: "{{ annotations['k8s.v1.cni.cncf.io/vrf'] | regex_search('\"label\": \"([^\"]+)\"', '\\1') }}"
    
    - name: Extract label with default and convert to string
      set_fact:
        label_value: "{{ (annotations['k8s.v1.cni.cncf.io/vrf'] | regex_search('\"label\": \"([^\"]+)\"', '\\1') | first) | default('default-label') | string }}"

    - name: Extract vrf_name with default and convert to string
      set_fact:
        vrf_name_value: "{{ (annotations['k8s.v1.cni.cncf.io/vrf'] | regex_search('\"vrf_name\": \"([^\"]+)\"', '\\1') | first) | default('default-vrf_name') | string }}"

    - name: Extract sz_type with default and convert to integer
      set_fact:
        sz_type_value: "{{ (annotations['k8s.v1.cni.cncf.io/vrf'] | regex_search('\"sz_type\": \"([^\"]+)\"', '\\1') | first) | default('100') | string }}"

    - name: Extract vrf_description with default and convert to string
      set_fact:
        vrf_description_value: "{{ (annotations['k8s.v1.cni.cncf.io/vrf'] | regex_search('\"vrf_description\": \"([^\"]+)\"', '\\1') | first) | default('default-vrf_description') | string }}"

    - name: Extract vni_id with default and convert to string
      set_fact:
        vni_id_value: "{{ (annotations['k8s.v1.cni.cncf.io/vrf'] | regex_search('\"vni_id\":\\s*([0-9]+)', '\\1')) | first | default(100000) | int }}"

    - name: Connect to Apstra
      junipernetworks.apstra.authenticate:
        verify_certificates: false
        logout: false
      register: auth

    - name: Get blueprint
      junipernetworks.apstra.blueprint:
          body:
            label: "eda-bp"
          auth_token: "{{ auth.token }}"
      register: bp

    - name: Create security_zone
      junipernetworks.apstra.security_zone:
        id: "{{ bp.id }}"
        body:
          vrf_name: "{{ vrf_name_value }}"
          vni_id: vni_id_value 
          vrf_description: "{{ vrf_description_value }}"
          sz_type: "{{ sz_type_value }}"
          label: "{{ label_value }}"
        auth_token: "{{ auth.token }}"
      register: sz

    - name: Create virtual_network
      junipernetworks.apstra.virtual_network:
        id: "{{ bp.id }}"
        body:
          label: "eda-demo-sample"
          description: "Create EDA VN sample"
          vn_type: "vxlan"
          security_zone_id: "{{ sz.id.security_zone }}"
        auth_token: "{{ auth.token }}"
      register: vn

    - name: Commit the blueprint
      junipernetworks.apstra.blueprint:
        id: "{{ bp.id }}"
        lock_state: "ignore"
        state: committed
        auth_token: "{{ auth.token }}"
      register: blueprint_commit

    - name: Logout of Apstra
      junipernetworks.apstra.authenticate:
        logout: true
        auth_token: "{{ auth.token }}"
