---
- name: Gather Apstra facts
  hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - junipernetworks.apstra
    - ansible.eda
    - dynatrace.event_driven_ansible
    - kubealex.eda
    - kubealex.general
    - redhatinsights.eda
    - sabre1041.eda
    - community.general
  environment:
    APSTRA_API_URL: "https://10.87.2.40/api"
    APSTRA_USERNAME: "admin"
    APSTRA_PASSWORD: "Apstramarvis@123"
    APSTRA_VERIFY_CERTIFICATES: 0
  vars:
    namespace: "{{ ns }}"
    annotations: "{{ annotate }}"
    event: "{{ ev }}"
  tasks:
    - name: Print the playbook name
      debug:
        msg: "Delete VNET"
    
    - name: Check if deletionTimestamp is defined
      ansible.builtin.set_fact:
        deletion_timestamp: "{{ event.metadata.deletionTimestamp | default(None) }}"

    - name: Exit if deletionTimestamp is defined
      ansible.builtin.meta: end_play
      when: deletion_timestamp is not none
      vars:
        msg: "Deletion timestamp found: {{ deletion_timestamp }}"

    - name: Display deletion timestamp
      ansible.builtin.debug:
        msg: "Deletion timestamp found: {{ deletion_timestamp }}"
      when: deletion_timestamp is not none