---
- name: Gather Apstra facts
  hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - junipernetworks.apstra
    - ansible.eda
    - dynatrace.event_driven_ansible
    - kubealex.eda
    - kubealex.general
    - redhatinsights.eda
    - sabre1041.eda
    - community.general
  environment:
    APSTRA_API_URL: "https://10.87.2.40/api"
    APSTRA_USERNAME: "admin"
    APSTRA_PASSWORD: "Apstramarvis@123"
    APSTRA_VERIFY_CERTIFICATES: 0
  vars:
    namespace: "{{ ns }}"
    annotations: "{{ annotate }}"
    event: "{{ ev }}"
  tasks:

    - name: Connect to Apstra
      junipernetworks.apstra.authenticate:
        verify_certificates: false
        logout: false
      register: auth

    - name: Extract blueprint with default and convert to string
      set_fact:
        bluprint_label_value: "{{ (annotations['k8s.v1.cni.cncf.io/ep'] | regex_search('\"blueprint\": \"([^\"]+)\"', '\\1') | first) | string }}"
    
    - name: Extract virtual network label value
      set_fact:
        vnet_label_value: "{{ (annotations['k8s.v1.cni.cncf.io/ep'] | regex_search('\"vnet_label\": \"([^\"]+)\"', '\\1') | first) | string }}"

    - name: Get blueprint
      junipernetworks.apstra.blueprint:
        body:
          label: "{{ bluprint_label_value }}"
        auth_token: "{{ auth.token }}"
      register: bp


    - name: Update an endpoint policy application point
      junipernetworks.apstra.endpoint_policy:
        id: "{{ bp.id }}"
        virtual_network_label: "{{ vnet_label_value }}"
        body:
          label: "pratik_policy"
        state: absent

    - name: Commit blueprint
      junipernetworks.apstra.blueprint:
        id: 
          blueprint: "4b954fc4-91ba-478e-9f25-3e78168f83ca"
        lock_state: "unlocked"
        state: committed
        auth_token: "{{ auth.token }}"
      register: blueprint_unlock
        