---
- name: Set resource quotas for a Kubernetes cluster for a namespace
  hosts: localhost
  gather_facts: no
  vars:
    namespace: "{{ ns }}"
    requests_cpu: '2'
    limits_cpu: '3'
    requests_memory: '5Gi'
    limits_memory: '10Gi'

  tasks:
    - debug:
        msg: "{{ namespace }}"
    - name: Set resource quotas
      kubernetes.core.k8s:
        api_version: v1
        kind: ResourceQuota
        namespace: "{{ namespace }}"
        name: resource-quota
        kubeconfig: /root/.kube/config
        state: present
        definition:
          spec:
            hard:
              "limits.cpu": "{{ limits_cpu }}"
              "limits.memory": "{{ limits_memory }}"
              "requests.cpu": "{{ requests_cpu }}"
              "requests.memory": "{{ requests_memory }}"
