---
- name: Gather Apstra facts
  hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - junipernetworks.apstra
    - ansible.eda
    - dynatrace.event_driven_ansible
    - kubealex.eda
    - kubealex.general
    - redhatinsights.eda
    - sabre1041.eda
    - community.general
  environment:
    APSTRA_API_URL: "https://10.87.2.40/api"
    APSTRA_USERNAME: "admin"
    APSTRA_PASSWORD: "Apstramarvis@123"
    APSTRA_VERIFY_CERTIFICATES: 0
  vars:
    namespace: "{{ ns }}"
    annotations: "{{ annotate }}"
    event: "{{ ev }}"
  tasks:
    - name: Get the name of the pod
      set_fact:
        pod_name: "{{ event.resource.metadata.name }}"

    - name: Get the name of the namespace
      set_fact:
        namespace: "{{ event.resource.metadata.namespace }}"

    - name: Wait for the pod to be Running 
      k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ namespace }}"
        name: "{{ pod_name }}"
        label_selectors:
          - type=eda
        wait: yes
        wait_timeout: 300
      register: pod_info

    - name: If pod is not running end the play
      meta: end_play
      when: pod_info.resources[0].status.phase != "Running"

    - name: Get the annotations of the pod
      set_fact:
        pod_annotations: "{{ pod_info.resources[0].metadata.annotations }}"

    - name: Extract network names from network-status annotation
      set_fact:
        network_names: >-
          {{
            pod_annotations['k8s.v1.cni.cncf.io/network-status'] | from_json | json_query("[].name")
          }}

    - name: Debug network names
      debug:
        msg: "Network names: {{ network_names }}"

    - name: Extract PCI address for each network (excluding ovn-kubernetes)
      set_fact:
        pci_addresses: >-
          {{
            pod_annotations['k8s.v1.cni.cncf.io/network-status'] | from_json | selectattr('name', 'ne', 'ovn-kubernetes') | selectattr('device-info.type', 'eq', 'pci') | map(attribute='device-info.pci.pci-address') | list
          }}

    - name: Debug PCI addresses
      debug:
        msg: "PCI addresses: {{ pci_addresses }}"

    - name: Extract node name from pod spec
      set_fact:
        node_name: "{{ pod_info.resources[0].spec.nodeName }}"

    - name: Debug node name
      debug:
        msg: "Node name: {{ node_name }}"

    - name: Get SriovNetworkNodeState for the node
      k8s_info:
        api_version: sriovnetwork.openshift.io/v1
        kind: SriovNetworkNodeState
        name: "{{ node_name }}"
        namespace: openshift-sriov-network-operator
      register: sriov_node_state

    - name: Initialize physical interfaces list
      set_fact:
        physical_interfaces: []

    - name: Extract physical interface for each PCI address
      set_fact:
        interfaces: "{{ sriov_node_state.resources[0].spec.interfaces }}"

    - name: Debug interfaces
      debug:
        msg: "Interfaces: {{ interfaces | to_json }}"
      
